import { TimeOption } from '@grafana/data';

import { ComboboxOption } from '../Combobox/types';

export const quickOptions: TimeOption[] = [
  { from: 'now-5m', to: 'now', display: 'Laatste 5 minuten' },
  { from: 'now-15m', to: 'now', display: 'Laatste 15 minuten' },
  { from: 'now-30m', to: 'now', display: 'Laatste 30 minuten' },
  { from: 'now-1h', to: 'now', display: 'Laatste 1 uur' },
  { from: 'now-3h', to: 'now', display: 'Laatste 3 uur' },
  { from: 'now-6h', to: 'now', display: 'Laatste 6 uur' },
  { from: 'now-12h', to: 'now', display: 'Laatste 12 uur' },
  { from: 'now-24h', to: 'now', display: 'Laatste 24 uur' },
  { from: 'now-2d', to: 'now', display: 'Laatste 2 dagen' },
  { from: 'now-7d', to: 'now', display: 'Laatste 7 dagen' },
  { from: 'now-30d', to: 'now', display: 'Laatste 30 dagen' },
  { from: 'now-90d', to: 'now', display: 'Laatste 90 dagen' },
  { from: 'now-6M', to: 'now', display: 'Laatste 6 maanden' },
  { from: 'now-1y', to: 'now', display: 'Laatste 1 jaar' },
  { from: 'now-2y', to: 'now', display: 'Laatste 2 jaar' },
  { from: 'now-5y', to: 'now', display: 'Laatste 5 jaar' },
  { from: 'now-1d/d', to: 'now-1d/d', display: 'Gisteren' },
  { from: 'now-2d/d', to: 'now-2d/d', display: 'Eergisteren' },
  { from: 'now-7d/d', to: 'now-7d/d', display: 'Deze dag vorige week' },
  { from: 'now-1w/w', to: 'now-1w/w', display: 'Vorige week' },
  { from: 'now-1M/M', to: 'now-1M/M', display: 'Vorige maand' },
  { from: 'now-1Q/fQ', to: 'now-1Q/fQ', display: 'Vorig fiscaal kwartaal' },
  { from: 'now-1y/y', to: 'now-1y/y', display: 'Vorig jaar' },
  { from: 'now-1y/fy', to: 'now-1y/fy', display: 'Vorig fiscaal jaar' },
  { from: 'now/d', to: 'now/d', display: 'Vandaag' },
  { from: 'now/d', to: 'now', display: 'Vandaag tot nu toe' },
  { from: 'now/w', to: 'now/w', display: 'Deze week' },
  { from: 'now/w', to: 'now', display: 'Deze week tot nu toe' },
  { from: 'now/M', to: 'now/M', display: 'Deze maand' },
  { from: 'now/M', to: 'now', display: 'Deze maand tot nu toe' },
  { from: 'now/y', to: 'now/y', display: 'Dit jaar' },
  { from: 'now/y', to: 'now', display: 'Dit jaar tot nu toe' },
  { from: 'now/fQ', to: 'now', display: 'Dit fiscale kwartaal tot nu toe' },
  { from: 'now/fQ', to: 'now/fQ', display: 'Dit fiscale kwartaal' },
  { from: 'now/fy', to: 'now', display: 'Dit fiscale jaar tot nu toe' },
  { from: 'now/fy', to: 'now/fy', display: 'Dit fiscale jaar' },
];

export const monthOptions: Array<ComboboxOption<number>> = [
  { label: 'Januari', value: 0 },
  { label: 'Februari', value: 1 },
  { label: 'Maart', value: 2 },
  { label: 'April', value: 3 },
  { label: 'Mei', value: 4 },
  { label: 'Juni', value: 5 },
  { label: 'Juli', value: 6 },
  { label: 'Augustus', value: 7 },
  { label: 'September', value: 8 },
  { label: 'Oktober', value: 9 },
  { label: 'November', value: 10 },
  { label: 'December', value: 11 },
];
